// Generated by CoffeeScript 1.6.3
exports.proto = {
  "new": function(object) {
    var child, key, value;
    child = Object.create(this);
    for (key in object) {
      value = object[key];
      child[key] = value;
    }
    if (typeof child.init === "function") {
      child.init();
    }
    return child;
  },
  as: function(object) {
    var child, key, value;
    child = Object.create(this);
    for (key in object) {
      value = object[key];
      child[key] = value;
    }
    return child;
  },
  "super": function(method) {
    var _base;
    if (method == null) {
      method = 'init';
    }
    return typeof (_base = this.__proto__)[method] === "function" ? _base[method]() : void 0;
  }
};
